### ISSUE TITLE
Can it be used for a non-modal species? 

### ISSUE THREAD

**Issue by Ram-Nagar** [genepi/haplogrep3#30]
I am working on a fungus where I would like to see mitochondrial haplotypes in the population and if heteroplasmy exists!
Also, how multi-sample variation should be called for detecting heteroplasmy. What ploidy I should use while calling the variations.
Thanks

**Comment by seppinho** [comment]
Hi, Haplogrep 3 is for haplogroup classification only, we do not detect heteroplasmy here.
