### ISSUE TITLE
Example VCF is Not VCF Format

### ISSUE THREAD

**Issue by DarioS** [genepi/haplogrep3#31]
It does not have the required columns `CHROM`, `POS`, `REF`, `ALT`, `QUAL`, `FILTER`, `INFO` and samples should be in columns, not rows.
![image](https://github.com/genepi/haplogrep3/assets/631218/48710799-ef9e-4d07-ad77-937132401752)

**Comment by seppinho** [comment]
Thats just a copy/paste error. The screenshot is for hsd above. If you are looking for vcf files, see here: https://github.com/genepi/haplogrep3/tree/main/test-data/vcf
