### ISSUE TITLE
Quality Formula Not Defined

### ISSUE THREAD

**Issue by DarioS** [genepi/haplogrep3#33]
The output has Quality column but how this is calculated doesn't appear to be defined anywhere. What is the mathemtical formula?
```
$ cat testOutput.txt 
"SampleID"      "Haplogroup"    "Rank"  "Quality"       "Range"
"7_21_11450"    "H"     "1"     "0.7604"        "1-16569"
"7_21_11555"    "H2a2a1"        "1"     "0.5000"        "1-16569"
"7_21_11556"    "H"     "1"     "0.7604"        "1-16569"
"7_21_11557"    "H2"    "1"     "0.8025"        "1-16569"
"7_21_11576"    "H2a"   "1"     "0.7423"        "1-16569"
"7_21_14555"    "H"     "1"     "0.9236"        "1-16569"
"7_21_14557"    "H"     "1"     "0.9236"        "1-16569"
"7_21_KOLF21"   "H"     "1"     "0.7604"        "1-16569"
"7_21_RM35"     "H2a2a" "1"     "1.0000"        "1-16569"
```
Some guidance for interpreting Quality should be provided in the documentation. What is the numeric range? What are bad values?

**Comment by seppinho** [comment]
Hi,
see docs: https://haplogrep.readthedocs.io/en/latest/kulczynski/. The formula is also defined in the init paper: https://onlinelibrary.wiley.com/doi/full/10.1002/humu.21382

best.
sebastian
