### ISSUE TITLE
haplogrep3 yaml 

### ISSUE THREAD

**Issue by squigzzz** [genepi/haplogrep3#36]
if I am running haplogrep3 within a container in an environment with tight security protocols, and I am getting frequent connection time outs is there any way to install the phylogenetic treees locally and point to them so that there is no need to connect and pull the trees every time ?

**Comment by jammywwh** [comment]
@seppinho Dear developer, hello, I have encountered a similar problem, always prompted "Loading configuration from file 'haplogrep3.yaml' failed.". I downloaded and decompressed it according to the documentation, even if I added./haplogrep3 install-tree phylotree-fu-rcrs@1.2, it still prompts this. Looking forward to your reply, thank you.

**Comment by seppinho** [comment]
Thanks both. We're installing the trees from Github using https://raw.githubusercontent.com. That means, when building the container, users need to have access to this URL. Using the latest version (v3.2.2) the installation of the treesis a  one-time task, all executions are then using the installed trees from the binary. In previous versions, trees are always downloaded into the working directory. 

Fyi, we used this setup e.g. for mtDNA-Server (https://github.com/genepi/mtdna-server-2/). The image is hosted on quay.io, therefore no installations are required by the end-user.

**Comment by Sofietb-work** [comment]
I'm having the same issue as jammywwh on Windows 10 Enterprise using both Oracle java 1.8 and openjdk java 22.0.1. I can access https://raw.githubusercontent.com/genepi/haplogrep-trees/main/trees.json from my machine. I tried removing all trees but one from the haplogrep3.yaml file and checked that I could download that tree from my browser.

Yet I get the following error:
```
Loading configuration from file 'haplogrep3.yaml' failed.
trees\2d52dfc5c711d7558e12f96d1f77baf3.yaml
```
