### ISSUE TITLE
Incomplete installation documentation or release packaging error.

### ISSUE THREAD

**Issue by vruano** [genepi/haplogrep3#37]
Hi, recently I downloaded v3.2.1 for linux a and followed the simple instruction given in [docs/installation.md](../tree/main/docs/installation.md).

However when executing haplogrep3 (without argument at least) it complains it cannot find ```tree.yaml```. 

``` 
$ ./haplogrep3
                                                                                             
Haplogrep 3 3.2.1                                                                                           
(c) 2022-2023 Sebastian Schönherr, Hansi Weissensteiner, Lukas Forer                                                                                                     
Loading configuration from file 'haplogrep3.yaml' failed.                        
/..../haplogrep3-3.2.1/trees/phylotree-fu-rcrs/1.2/tree.yaml (No such file or directory) `
```
It turns out that there is another zip file ```./trees/phylotree-fu-rcrs/1.2/package.zip``` that when unzipped at its parent directory produces the missing yaml together with other files that overwrite some files that are already "unzip".

I guess the best course of action would be remove the second unzip step and include every needed file directly in the main zip file.

**Comment by gqworks** [comment]
I encountered the same error message, and was able to resolve it by running haplogrep with sudo.
`sudo ./haplogrep3`

**Comment by vruano** [comment]
> I encountered the same error message, and was able to resolve it by running haplogrep with sudo. `sudo ./haplogrep3`

That does not seem to follow best practices; sudo should not be necessary. 
I will retry with the latest myself and report here.

**Comment by vruano** [comment]
I can confirm that now using the latest seem to work for me v3.2.2 or at least I get to the point it shows the list of commands.
Will close issue but @gqworks an any-other is welcome to reopen if they feel it needs to be.
