### ISSUE TITLE
Example use of `--phylotree` argument

### ISSUE THREAD

**Issue by mfansler** [genepi/haplogrep3#39]
I am unable to find in the documentation how exactly a phylotree should be specified in the `--phylotree` argument of `haplogrep classify`.

For example, all the following fail:

```
--phylotree=phylotree-rcrs@17.2
--phylotree=rcrs@17.2
--phylotree=phylotree-rcrs/17.2
--phylotree=rcrs/17.2
--phylotree=-rcrs/17.2
--phylotree=trees/phylotee-rcrs/17.2/tree.xml
--phylotree=trees/phylotee-rcrs/17.2/tree
```

Clearly stabbing in the dark here where a simple example would alleviate this.

**Comment by haansi** [comment]
Hi, sorry for the inconvenience - you are right, we are missing an example - the correct parameter is "--tree" - see here: https://haplogrep.readthedocs.io/en/latest/parameters/ 

besides `--input` and `--output `values you can specify it this this way:

|parameter | explanation |
|---|---|
| `--tree phylotree-rcrs@17.2 ` |  Phylogenetic Tree by Mannis van Oven, with some minor fixes (~5400 haplogroups included) see here https://haplogrep.i-med.ac.at/phylogenies/phylotree-rcrs@17.2 |
|`--tree phylotree-fu-rcrs@1.2 ` |Phylogenetic Forensic Updated Tree by Duer et al including ~6380 haplogroups see here https://haplogrep.i-med.ac.at/phylogenies/phylotree-fu-rcrs@1.2 |
